### ISSUE TITLE
Ansifying SQL

### ISSUE THREAD

**Issue by sternix** [AnowarCST/moodle-quizaccess_eproctoring#6]
Hi, i tested this plugin with moodle 3.10 with PostgreSQL database setup,
i get SQL errors in report.php file
when i changed 3 sql commands with below ones, sql errors gone,
can you test this sql's with your setup,
it can work with other database setups i think,

Best Regards

1-) in line 75

$sql = "SELECT e.id as reportid, e.userid as studentid, e.webcampicture as webcampicture, e.status as status,
         e.timemodified as timemodified, u.firstname as firstname, u.lastname as lastname, u.email as email
         from  {quizaccess_proctoring_logs} e INNER JOIN {user} u WHERE u.id = e.userid
         AND e.courseid = '$courseid' AND e.quizid = '$cmid' AND u.id = '$studentid' && e.id = '$reportid'";

--->

$sql = "SELECT
                    e.id as reportid,
                    e.userid as studentid,
                    e.webcampicture as webcampicture,
                    e.status as status,
                    e.timemodified as timemodified,
                    u.firstname as firstname,
                    u.lastname as lastname,
                    u.email as email
                FROM
                    {quizaccess_proctoring_logs} e INNER JOIN {user} u ON (u.id = e.userid)
                WHERE
                    e.courseid = '$courseid'
                    AND e.quizid = '$cmid'
                    AND u.id = '$studentid'
                    AND e.id = '$reportid'";

2-)  in line 83 
   $sql = "SELECT e.id as reportid, e.userid as studentid, e.webcampicture as webcampicture, e.status as status,
         e.timemodified as timemodified, u.firstname as firstname, u.lastname as lastname, u.email as email
         from  {quizaccess_proctoring_logs} e INNER JOIN {user} u WHERE u.id = e.userid
         AND e.courseid = '$courseid' AND e.quizid = '$cmid' group by e.userid";

--->

   $sql = "SELECT
                    e.id as reportid,
                    e.userid as studentid,
                    e.webcampicture as webcampicture,
                    e.status as status,
                    e.timemodified as timemodified,
                    u.firstname as firstname,
                    u.lastname as lastname,
                    u.email as email
                FROM
                    {quizaccess_proctoring_logs} e INNER JOIN {user} u ON (u.id = e.userid)
                WHERE
                    u.id = e.userid
                    AND e.courseid = '$courseid'
                    AND e.quizid = '$cmid'
                GROUP BY
                    e.id, e.userid, e.webcampicture, e.status, e.timemodified, u.firstname, u.lastname, u.email";

3-) in line 132
  $sql = "SELECT e.id as reportid, e.userid as studentid, e.webcampicture as webcampicture, e.status as status,
        e.timemodified as timemodified, u.firstname as firstname, u.lastname as lastname, u.email as email
        from {quizaccess_proctoring_logs} e INNER JOIN {user} u WHERE u.id = e.userid
        AND e.courseid = '$courseid' AND e.quizid = '$cmid' AND u.id = '$studentid'";

--->

 $sql = "SELECT
                    e.id as reportid,
                    e.userid as studentid,
                    e.webcampicture as webcampicture,
                    e.status as status,
                    e.timemodified as timemodified,
                    u.firstname as firstname,
                    u.lastname as lastname,
                    u.email as email
                FROM
                    {quizaccess_proctoring_logs} e INNER JOIN {user} u ON (u.id = e.userid)
                WHERE
                    e.courseid = '$courseid'
                    AND e.quizid = '$cmid'
                    AND u.id = '$studentid'";

**Comment by AnowarCST** [comment]
Please put your issue in our updated repository. 
https://github.com/eLearning-BS23/moodle-quizaccess_proctoring
